<script lang="ts">
  import { ArrowRight, Icon, QuestionMarkCircle } from 'svelte-hero-icons';
  import { Tooltip } from 'svelte-tooltip-simple';
  import { Colors, PillTypes } from '$lib/enums';
  import { Pill, YouTubeEmbed, Button, TokenLogo } from '$lib/components';

  export let tokenLogo = '';
  export let actionFunc = () => {};
  export let youtubeEmbedID: string = '';
  export let title = 'Title';
  export let callToActionText = 'Continue';
  export let apr: string = '';
  export let soon: boolean = false;
</script>

<article class="rounded-2xl bg-card p-4 text-white lg:p-6">
  <div class="mb-2 flex items-center justify-between">
    <div class="flex items-center">
      {#if tokenLogo}
        <div class="mr-2 h-8 w-8">
          <TokenLogo name={tokenLogo} />
        </div>
      {/if}
      <h3 class="whitespace-nowrap text-xl font-semibold">
        {title}
      </h3>
      {#if soon}
        <div class="ml-3">
          <Pill type={PillTypes.Warning}>Coming soon</Pill>
        </div>
      {/if}
    </div>
    {#if apr}
      <div class="flex items-center justify-center gap-2">
        <span class="w-full whitespace-nowrap text-sm">APR {apr}%</span>
        <Tooltip>
          <div class="h-4 w-4">
            <Icon src={QuestionMarkCircle} class="cursor-pointer text-white" />
          </div>
          <svelte:fragment slot="content">
            <div class="max-w-xs">
              Annual percentage rate (APR) refers to the yearly interest generated by a sum that's
              charged to borrowers or paid to investors. APR is expressed as a percentage that
              represents the actual yearly cost of funds over the term of a loan or income earned on
              an investment. This includes any fees or additional costs associated with the
              transaction but does not take compounding into account. The APR provides consumers
              with a bottom-line number they can compare among lenders, credit cards, or investment
              products.
            </div>
          </svelte:fragment>
        </Tooltip>
      </div>
    {/if}
  </div>

  <div class="mb-3 text-sm">
    <slot name="description" />
  </div>

  {#if youtubeEmbedID}
    <div class="mb-4">
      <YouTubeEmbed id={youtubeEmbedID} />
    </div>
  {/if}

  <div class="flex gap-3">
    <Button full on:click={actionFunc} icon={ArrowRight} color={Colors.Green} iconRight>
      {callToActionText}
    </Button>
  </div>
</article>
